title: Legend Labs
logo: /assets/img/legend-logo.jpg
description: Never stagnate, always keep improving.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
