title: Tyler Hardy
logo: /assets/img/legend-logo.jpg
description: Cybersecurity professional, always keep improving.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme